# Generated by Django 5.1.2 on 2024-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basesettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сайта')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('facebook', models.URLField(verbose_name='Ссылка на facebook')),
                ('twitter', models.URLField(verbose_name='Ссылка на twitter')),
                ('github', models.URLField(verbose_name='Ссылка на Github')),
                ('google', models.URLField(verbose_name='Ссылка на Google +')),
            ],
            options={
                'verbose_name': 'Основная настройка сайта',
                'verbose_name_plural': 'Основные настройки сайта',
            },
        ),
    ]
